questions =  [
    {"id": 0, "I wouldn't mind joining the Borg.", "effects": {"right": -67320, "auth": 67320}},
    {"id": 1, "I do not believe in individuality.", "effects": {"right": -58905, "auth": 67320}},
    {"id": 2, "I want to join a hive mind.", "effects": {"right": -50490, "auth": 67320}},
    {"id": 3, "Only class matters. Not gender, not race, not name, only class.", "effects": {"right": -42075, "auth": 67320}},
    {"id": 4, "Collectivism is my religion.", "effects": {"right": -33660, "auth": 67320}},
    {"id": 5, "I worship the State.", "effects": {"right": -25245, "auth": 67320}},
    {"id": 6, "IngSoc is based.", "effects": {"right": -16830, "auth": 67320}},
    {"id": 7, "Ignorance is strength.", "effects": {"right": -8415, "auth": 67320}},
    {"id": 8, "The party is always right.", "effects": {"auth": 67320}},
    {"id": 9, "The party should be able to kill whomever they please.", "effects": {"right": 8415, "auth": 67320}},
    {"id": 10, "Free will is dangerous and should be disposed of.", "effects": {"right": 16830, "auth": 67320}},
    {"id": 11, "The burgundian system is based.", "effects": {"right": 25245, "auth": 67320}},
    {"id": 12, "The weak should die.", "effects": {"right": 33660, "auth": 67320}},
    {"id": 13, "Might makes right.", "effects": {"right": 42075, "auth": 67320}},
    {"id": 14, "War needs no justification.", "effects": {"right": 50490, "auth": 67320}},
    {"id": 15, "The governement should perform human sacrifices.", "effects": {"right": 58905, "auth": 67320}},
    {"id": 16, "Warhammer 40000 is a goal.", "effects": {"right": 67320, "auth": 67320}},
    {"id": 17, "The governement should own literally everything.", "effects": {"right": -67320, "auth": 58905}},
    {"id": 18, "I defend Stalin.", "effects": {"right": -58905, "auth": 58905}},
    {"id": 19, "Social credit (like in China) is a good idea.", "effects": {"right": -50490, "auth": 58905}},
    {"id": 20, "Kulaks deserved their fate.", "effects": {-42075, "auth": 58905}},
    {"id": 21, "", "effects": {}},
    {"id": 22, "", "effects": {}},
    {"id": 23, "", "effects": {}},
    {"id": 24, "", "effects": {}},
    {"id": 25, "", "effects": {}},
    {"id": 26, "", "effects": {}},
    {"id": 27, "", "effects": {}},
    {"id": 28, "", "effects": {}},
    {"id": 29, "", "effects": {}},
    {"id": 30, "", "effects": {}},
    {"id": 31, "", "effects": {}},
    {"id": 32, "", "effects": {}},
    {"id": 33, "", "effects": {}},
    {"id": 34, "", "effects": {}},
    {"id": 35, "", "effects": {}},
    {"id": 36, "", "effects": {}},
    {"id": 37, "", "effects": {}},
    {"id": 38, "", "effects": {}},
    {"id": 39, "", "effects": {}},
    {"id": 40, "", "effects": {}},
    {"id": 41, "", "effects": {}},
    {"id": 42, "", "effects": {}},
    {"id": 43, "", "effects": {}},
    {"id": 44, "", "effects": {}},
    {"id": 45, "", "effects": {}},
    {"id": 46, "", "effects": {}},
    {"id": 47, "", "effects": {}},
    {"id": 48, "", "effects": {}},
    {"id": 49, "", "effects": {}},
    {"id": 50, "", "effects": {}},
    {"id": 51, "", "effects": {}},
    {"id": 52, "", "effects": {}},
    {"id": 53, "", "effects": {}},
    {"id": 54, "", "effects": {}},
    {"id": 55, "", "effects": {}},
    {"id": 56, "", "effects": {}},
    {"id": 57, "", "effects": {}},
    {"id": 58, "", "effects": {}},
    {"id": 59, "", "effects": {}},
    {"id": 60, "", "effects": {}},
    {"id": 61, "", "effects": {}},
    {"id": 62, "", "effects": {}},
    {"id": 63, "", "effects": {}},
    {"id": 64, "", "effects": {}},
    {"id": 65, "", "effects": {}},
    {"id": 66, "", "effects": {}},
    {"id": 67, "", "effects": {}},
    {"id": 68, "", "effects": {}},
    {"id": 69, "", "effects": {}},
    {"id": 70, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
    {"id": 0, "", "effects": {}},
];
